# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxC6G1uY9coo2MJn7rW6SnELikhW__ek
"""

import streamlit as st
import os

FILENAME = "tasks.txt"

# Load tasks from file
def load_tasks():
    if os.path.exists(FILENAME):
        with open(FILENAME, "r") as file:
            return [line.strip() for line in file.readlines()]
    return []

# Save tasks to file
def save_tasks(tasks):
    with open(FILENAME, "w") as file:
        for task in tasks:
            file.write(task + "\n")

# Main Streamlit UI
st.title("📝 To-Do List App")

tasks = load_tasks()

# Input for adding new task
new_task = st.text_input("Enter a new task:")

if st.button("Add Task"):
    if new_task:
        tasks.append(new_task)
        save_tasks(tasks)
        st.success("✅ Task added!")
        st.rerun() 
    else:
        st.warning("⚠️ Task cannot be empty.")

# Display and delete tasks
st.subheader("📋 Your Tasks")
if tasks:
    for i, task in enumerate(tasks):
        col1, col2 = st.columns([0.8, 0.2])
        with col1:
            st.write(f"{i+1}. {task}")
        with col2:
            if st.button("🗑️ Delete", key=f"del_{i}"):
                tasks.pop(i)
                save_tasks(tasks)
                st.success("Task deleted.")
                st.experimental_rerun()
else:
    st.info("No tasks yet. Add one!")