# -*- coding: utf-8 -*-
"""To-Do List CLI App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KY01ANiGgx9E77WjfjdWfiNhwf-FI5ZW
"""

# ✅ To-Do List CLI App
FILENAME = "tasks.txt"

# Load tasks from file
def load_tasks():
    try:
        with open(FILENAME, "r") as file:
            tasks = [line.strip() for line in file.readlines()]
    except FileNotFoundError:
        tasks = []
    return tasks

# Save tasks to file
def save_tasks(tasks):
    with open(FILENAME, "w") as file:
        for task in tasks:
            file.write(task + "\n")

# Show menu
def show_menu():
    print("\n--- 📋 To-Do List Menu ---")
    print("1️⃣  View Tasks")
    print("2️⃣  Add Task")
    print("3️⃣  Delete Task")
    print("4️⃣  Exit")

# Main logic
def main():
    tasks = load_tasks()

    while True:
        show_menu()
        choice = input("Enter your choice (1-4): ")

        if choice == "1":
            if not tasks:
                print("📭 No tasks yet.")
            else:
                print("\n📝 Tasks:")
                for idx, task in enumerate(tasks, 1):
                    print(f"{idx}. {task}")

        elif choice == "2":
            task = input("Enter new task: ")
            if task.strip():
                tasks.append(task)
                save_tasks(tasks)
                print("✅ Task added.")
            else:
                print("⚠️ Task cannot be empty.")

        elif choice == "3":
            if not tasks:
                print("⚠️ No tasks to delete.")
                continue
            for idx, task in enumerate(tasks, 1):
                print(f"{idx}. {task}")
            try:
                del_idx = int(input("Enter task number to delete: ")) - 1
                if 0 <= del_idx < len(tasks):
                    removed = tasks.pop(del_idx)
                    save_tasks(tasks)
                    print(f"🗑️ Deleted task: {removed}")
                else:
                    print("❌ Invalid task number.")
            except ValueError:
                print("❌ Please enter a valid number.")

        elif choice == "4":
            print("👋 Exiting... Goodbye!")
            break

        else:
            print("❗ Invalid choice. Please enter 1–4.")

# Run the app
main()